# Website info
title: Glitch Theme
acronym: gh
tagline: A simple and cool theme for Jekyll and GitHub Pages.
email: hey@miltonolaf.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

paginate: 6
paginate_path: /blog/:num/
# Social users - twitter, instagram, github, gitlab, codepen profile, youtube and facebook
social:
  twitter: olafmilton
  github: miltonolaf
  linkedin: username
  youtube_user: username
  # youtube_channel: channel
  gitlab: username
  codepen: username
  facebook: miltonolaf
  instagram: username


favicon: favicon.png # favicon name in assets/img/

permalink: /:year/:month/:title/
jekyll-archives:
  enabled: all
  layouts:
    year: archive
    month: archive
    day: archive
    tag: tag
    category: archive
  permalinks:
    year: /:year/
    month: /:year/:month/
    day: /:year/:month/:day/
    tag: /tags/:name/
    category: /:name/

# Assets - We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed
# Build settings
env: development
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - .git*
  - .gitignore
