# Website info
title: Glitch Theme
tagline: A simple and cool theme for Jekyll and GitHub Pages.
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/glitch-jekyll" # the subpath of your site, e.g. /blog
url: "http://miltonolaf.com/glitch-jekyll" # the base hostname & protocol for your site, e.g. http://example.com

paginate: 5
paginate_path: /blog/:num/

# Social users - twitter, instagram, github, gitlab, codepen profile, youtube and facebook
social:
  twitter: olafmilton
  github: miltonolaf
  linkedin: username
  youtube_user: username
  # youtube_channel: channel
  gitlab: username
  codepen: username
  facebook: miltonolaf
  instagram: username


favicon: favicon.png # favicon name in assets/img/

# Assets - We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - .git*
  - .gitignore
